version: "3.8"
services:
    web:
        build:
            context: .
        environment:
            - VALO_APP_GATEWAY_ADDRESS=<ip address>
            - VALO_APP_GATEWAY_SECURITY_CODE=<security code>
        network_mode: host
